version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    image: fc99ab500833
    volumes:
      - /home/adri/Documents/HtmlVladi:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: my_database
        MYSQL_USER: adri
        MYSQL_PASSWORD: 1234
    ports:
        - "9906:3306"
